apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: service-collector
    app.kubernetes.io/instance: jaeger-all-in-one-inmemory
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: jaeger-all-in-one-inmemory-collector
    app.kubernetes.io/part-of: jaeger
  name: jaeger-all-in-one-collector
spec:
  port:
    targetPort: http-c-binary-trft
  to:
    kind: Service
    name: jaeger-all-in-one-inmemory-collector
    weight: 100
  wildcardPolicy: None