apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: jaeger
  name: jaeger-all-in-one-collector
spec:
  port:
    targetPort: http-c-binary-trft
  to:
    kind: Service
    name: jaeger-all-in-one-inmemory-collector
    weight: 100
  wildcardPolicy: None