apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
  name: rhsi-hackfest-tenant
spec:
  email: admin@hackfest.example.com
  masterCredentialsRef:
    name: system-seed
    namespace: rhsi-hackfest-3scale-amp
  organizationName: rhsi-hackfest
  passwordCredentialsRef:
    name: tenant-admin-secret
    namespace: rhsi-hackfest-3scale-amp
  systemMasterUrl: 'https://master.apps.cluster-8bcs7.8bcs7.sandbox2056.opentlc.com'
  tenantSecretRef:
    name: tenant-secret
  username: admin
