apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: "RHSI Hackfest - API Backend services"
  name: rhsi-hackfest-apibackend
spec: {}