apiVersion: capabilities.3scale.net/v1beta1
kind: ActiveDoc
metadata:
  name: library-books-api
spec:
  providerAccountRef:
    name: tenant-secret
  activeDocOpenAPIRef:
    url: >-
      https://raw.githubusercontent.com/jeanNyil/rhsi-hackfest-nov2023/main/ThreescaleAPIProducts/library-books-api/threescale/openapi/LibraryBooksAPI_v2.yaml
  name: Library Books API (v2)
  productSystemName: library-books-api
  published: true
  systemName: librarybooksapi